os: osx
script:
- brew cask install homebrew/cask-versions/java8
- brew install openapi-generator
- mkdir html
- "./build.sh"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  local-dir: html
  on:
    branch: master
env:
  global:
    secure: z2NBRgteKo7GzwL2KYAQyOTzxx/nzKwXaRIDM7gPqvukQ9XZhT+Tz8insrTLm5nfWQWlUrKIqpGn93QR7uO6LAcQ7ryyoGHt2XM6T59Z8uiIzMap0TZ/Ft1Ac93xdU3HwVfhzIJqDSv6c8VIoXS6lwqTYjgTiJEO7TyBSqA6yBzltzqjtRD4R/yPbdu99NGnHFSXhFgDhsfblxRbrNWi85NBoPEfFoYASKJFW39CVvBrd8rG0fiC+xte6x0kYciVWplzBkIdMzQ4IkSjsRXZmUZjp4qyzGlMeyMcTtUpLJ+39XRKcCrBDNL4SvEfrQVfrKBuyELkKUJ4jxzRnJ1k+nHNqJi+zJBjZoM/XZLMh9CGT9ssGQFhv6Cu6zSKX9HfT2hliUFkbntvqa/KjFOnU9cL1KvFTEVXuoUXqNWJHHHa6XHd/fHGF6jRlLMWauiuScSQCCLFe1JiipyIXxDu3N2cvYyIRyO1/YqwMc9VKO5coy6EoMfaZXrAyhcUqMoxvUZQ6kOfvEaZH7espF/bpLA89Fraz7FKbkepL5sPiaSGaCFlqW2rUTRhn55Qm+n6XKw9Rw/E2qT8Fp1LFIevqZte613jZiYS55Xor7Vm6meoSwn3Mt8lmHv0lw3JORjBFVN0ZXajGAbQhcqv1DAG+isisAmiON7ay5jYl9JQciI=
