os: osx
script:
- brew cask install homebrew/cask-versions/java8
- brew install openapi-generator
- mkdir html
- "./build.sh"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  local-dir: html
  on:
    branch: master
env:
  global:
    secure: AXfo/tnjJDqTyHZcdEwiQFY9DZZ42/eadRqWYgUeoz0iO2l5/RCjz4uhKpP4mE+/kSOqiQjcGH/An2NRY+RYsKR5iOSe6WBef4S1WMZHdbeuliq1Ez4Y9rSLFrL1xs5RDu3HlbXKQ+2eorO+JiymsQjXmhymLrnOvqiAP9zM0vVllojU78EO1JhhtTcXvOrz7gSjXgiEsWDOpMK66ns+IC13Dl3WHQ2UebZIOFxRowFqz/xqXIoDpJLtEox7HCmYYF0ktq0S1unO5EXSwDVgxI5rVsLe8o1aTXdNNR+gsMMaZQ+9144eflxQMY6Ptvyrk9joQ1B86G3AKErHcgsC+FnLgT4Bc176b4B5nAjggPfg8idLKNuGujkNRwTSdGvxZ69WtkeZycf6mfuz47YBWHhgOKY67boHbcPmoCWfFf+vFtkwHNw7z7KVPVAainSsOBVC4BaGTlXXMhRPlk4Mvyk2HwJoddREg+yeHSSja05EeZvRZa0m8n+LzQ0wWwi1ckAhcOt1zaiEpQDmt4mItvJdxxFqMXJE3GrAAoYRcVo4ZOiUa7C6zXcv6e7YT53b0GnnpOEyOgfflWedqFyM7q74tcTRzLkmx4Mgzr5Nz2q6jjaynUHJJKGLl2a5lCFZ0Gbemit0Qttgt2K+KLdK6/KgndqUPCQW810BYwfVyMg=
