openapi: 3.0.1
info:
  description: This is OpenAPI test
  version: 1.0.0
  title: OpenAPI test
  contact:
    url: https://github.com/MartinDelille/openapi-test
    email: "martin@lylo.tv"
components:
  schemas:
    User:
      title: An user
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          example: '01srv001'
        name:
          type: string
          example: 'Martin Delille'
paths:
  /users/me:
    get:
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
